In [21]:
import sqlite3
import numpy as np
import pandas as pd

def nagruzka(name_list,k,cosa,m):
    Unom = 10
    res_list = []
    with open(name_list, 'r', encoding='utf-8') as f:
        with sqlite3.connect("server_db.db") as my_data:
            sql = my_data.cursor()
            for i in f.readlines():
                if i.strip().split()[1] == '0':
                    res_list.append(0)
                elif len(i.strip().split()[1:]) == 1 and i.strip().split()[1].endswith('n') == False:
                    sql.execute(f"SELECT s FROM trans2 WHERE mark_trans = '{i.strip().split()[1]}'")
                    res_list.append(float(sql.fetchone()[0]))
                elif len(i.strip().split()[1:]) == 1 and i.strip().split()[1].endswith('n') == True:
                    sql.execute(f"SELECT pxx,qxx FROM trans2 WHERE mark_trans = '{i.strip().split()[1][:-1]}'")
                    pxx, qxx = map(float, sql.fetchone())
                    res_list.append(complex(pxx, qxx))
                else:
                    my_list = (i.strip().split()[1:])
                    my_list.remove("+")
                    result = 0
                    for i in my_list:
                        sql.execute(f"SELECT pxx,qxx FROM trans2 WHERE mark_trans = '{i}'")
                        pxx, qxx = map(float, sql.fetchone())
                        result += complex(pxx, qxx)
                    res_list.append(result)

    res_list.remove(0)
    
    Icp_max = (sum(res_list)*k)/(Unom*pow(3,0.5))
    Iнб = [(Icp_max*i)/sum(res_list) for i in res_list]
    Pнб = [i*cosa*Unom*pow(3,0.5) for i in Iнб]
    Qнб = [i*(1-cosa**2)**0.5*Unom*pow(3,0.5) for i in Iнб]
    Sнб = np.rot90(np.array([[complex(Pнб[i],Qнб[i]) for i in range(len(Pнб))]]),k=-1)
    Sнм = Sнб * m
    
    
    
    
    
    
    return -Sнб,-Sнм


def main():
    name_nagruzka = 'нагрузки.txt'
    print(nagruzka(name_list=name_nagruzka,k=0.65,cosa = 0.91,m = 0.2))


if __name__ == "__main__":
    main()


(array([[  -0.     -0.j        ],
       [  -0.     -0.j        ],
       [-147.875 -67.37384044j],
       [  -0.     -0.j        ],
       [ -14.7875 -6.73738404j],
       [  -0.     -0.j        ],
       [  -0.     -0.j        ],
       [  -0.     -0.j        ],
       [ -59.15  -26.94953617j],
       [  -0.     -0.j        ],
       [-147.875 -67.37384044j],
       [  -0.     -0.j        ],
       [ -37.2645-16.97820779j],
       [  -0.     -0.j        ],
       [ -14.7875 -6.73738404j],
       [  -0.     -0.j        ],
       [-147.875 -67.37384044j],
       [  -0.     -0.j        ],
       [  -0.     -0.j        ],
       [ -59.15  -26.94953617j],
       [ -23.66  -10.77981447j],
       [  -0.     -0.j        ],
       [ -37.2645-16.97820779j],
       [  -0.     -0.j        ],
       [-147.875 -67.37384044j],
       [  -0.     -0.j        ],
       [  -0.     -0.j        ],
       [ -59.15  -26.94953617j],
       [  -0.     -0.j        ],
       [ -37.2645-16.97820779j],
       [ 

Функция возвращает нагрузки(наибольшие и наименьшие) в виде матриц

In [39]:
name_nagruzka = 'нагрузки.txt'
Sнб,Sнм = nagruzka(name_list=name_nagruzka,k=0.65,cosa = 0.91,m = 0.2)
Unom = 10

In [23]:
Sнб

array([[  -0.     -0.j        ],
       [  -0.     -0.j        ],
       [-147.875 -67.37384044j],
       [  -0.     -0.j        ],
       [ -14.7875 -6.73738404j],
       [  -0.     -0.j        ],
       [  -0.     -0.j        ],
       [  -0.     -0.j        ],
       [ -59.15  -26.94953617j],
       [  -0.     -0.j        ],
       [-147.875 -67.37384044j],
       [  -0.     -0.j        ],
       [ -37.2645-16.97820779j],
       [  -0.     -0.j        ],
       [ -14.7875 -6.73738404j],
       [  -0.     -0.j        ],
       [-147.875 -67.37384044j],
       [  -0.     -0.j        ],
       [  -0.     -0.j        ],
       [ -59.15  -26.94953617j],
       [ -23.66  -10.77981447j],
       [  -0.     -0.j        ],
       [ -37.2645-16.97820779j],
       [  -0.     -0.j        ],
       [-147.875 -67.37384044j],
       [  -0.     -0.j        ],
       [  -0.     -0.j        ],
       [ -59.15  -26.94953617j],
       [  -0.     -0.j        ],
       [ -37.2645-16.97820779j],
       [  

In [24]:
Sнм

array([[ -0.     -0.j        ],
       [ -0.     -0.j        ],
       [-29.575 -13.47476809j],
       [ -0.     -0.j        ],
       [ -2.9575 -1.34747681j],
       [ -0.     -0.j        ],
       [ -0.     -0.j        ],
       [ -0.     -0.j        ],
       [-11.83   -5.38990723j],
       [ -0.     -0.j        ],
       [-29.575 -13.47476809j],
       [ -0.     -0.j        ],
       [ -7.4529 -3.39564156j],
       [ -0.     -0.j        ],
       [ -2.9575 -1.34747681j],
       [ -0.     -0.j        ],
       [-29.575 -13.47476809j],
       [ -0.     -0.j        ],
       [ -0.     -0.j        ],
       [-11.83   -5.38990723j],
       [ -4.732  -2.15596289j],
       [ -0.     -0.j        ],
       [ -7.4529 -3.39564156j],
       [ -0.     -0.j        ],
       [-29.575 -13.47476809j],
       [ -0.     -0.j        ],
       [ -0.     -0.j        ],
       [-11.83   -5.38990723j],
       [ -0.     -0.j        ],
       [ -7.4529 -3.39564156j],
       [ -0.     -0.j        ],
       [

Создаем матрицу С (матрицу коэффициентов токораспределения)

In [25]:
def first_matrix(model):
    start, end = [int(i.split('-')[0]) for i in model], [int(i.split('-')[1]) for i in model]
    M = np.zeros(shape=[max(end), max(start)])
    try:
        for i in range(len(start)):
            M[start[i]-1,i] = 1
            M[end[i]-1, i] = -1

        M = M[1:, :].astype(np.int32)

        return np.linalg.inv(M)
    except Exception as ex:

        return "Something_wrong"

def main():
    model =  "1-2 2-3 3-4 2-5 5-6 5-7 "\
        "7-8 8-9 9-10 8-11 11-12 7-13 13-14 7-15 "\
        "15-16 15-17 17-18 15-19 19-20 20-21 19-22 19-23 23-24 "\
        "23-25 25-26 25-27 27-28 28-29 27-30 30-31 "\
        "23-32 32-33 33-34 32-35 35-36 35-37 37-38".split()
    print(first_matrix(model))

if __name__ == '__main__':
    main()

[[-1. -1. -1. ... -1. -1. -1.]
 [-0. -1. -1. ... -0. -0. -0.]
 [-0. -0. -1. ... -0. -0. -0.]
 ...
 [-0. -0. -0. ... -1. -0. -0.]
 [-0. -0. -0. ... -0. -1. -1.]
 [-0. -0. -0. ... -0. -0. -1.]]


Нумерация ветвей

In [26]:
model =  "1-2 2-3 3-4 2-5 5-6 5-7 "\
        "7-8 8-9 9-10 8-11 11-12 7-13 13-14 7-15 "\
        "15-16 15-17 17-18 15-19 19-20 20-21 19-22 19-23 23-24 "\
        "23-25 25-26 25-27 27-28 28-29 27-30 30-31 "\
        "23-32 32-33 33-34 32-35 35-36 35-37 37-38".split()
model

['1-2',
 '2-3',
 '3-4',
 '2-5',
 '5-6',
 '5-7',
 '7-8',
 '8-9',
 '9-10',
 '8-11',
 '11-12',
 '7-13',
 '13-14',
 '7-15',
 '15-16',
 '15-17',
 '17-18',
 '15-19',
 '19-20',
 '20-21',
 '19-22',
 '19-23',
 '23-24',
 '23-25',
 '25-26',
 '25-27',
 '27-28',
 '28-29',
 '27-30',
 '30-31',
 '23-32',
 '32-33',
 '33-34',
 '32-35',
 '35-36',
 '35-37',
 '37-38']

In [27]:
C = first_matrix(model=model)
C

array([[-1., -1., -1., ..., -1., -1., -1.],
       [-0., -1., -1., ..., -0., -0., -0.],
       [-0., -0., -1., ..., -0., -0., -0.],
       ...,
       [-0., -0., -0., ..., -1., -0., -0.],
       [-0., -0., -0., ..., -0., -1., -1.],
       [-0., -0., -0., ..., -0., -0., -1.]])

Найдем потоки, которые протекают по нашим ветвям в режимах наибольших и меньших нагрузок

In [28]:
Svнб =  C.dot(Sнб)
Svнб.real

array([[1111.4285],
       [ 147.875 ],
       [ 147.875 ],
       [ 963.5535],
       [  14.7875],
       [ 948.766 ],
       [ 207.025 ],
       [  59.15  ],
       [  59.15  ],
       [ 147.875 ],
       [ 147.875 ],
       [  37.2645],
       [  37.2645],
       [ 704.4765],
       [  14.7875],
       [ 147.875 ],
       [ 147.875 ],
       [ 541.814 ],
       [  59.15  ],
       [  59.15  ],
       [  23.66  ],
       [ 459.004 ],
       [  37.2645],
       [ 244.2895],
       [ 147.875 ],
       [  96.4145],
       [  59.15  ],
       [  59.15  ],
       [  37.2645],
       [  37.2645],
       [ 177.45  ],
       [ 147.875 ],
       [ 147.875 ],
       [  29.575 ],
       [  14.7875],
       [  14.7875],
       [  14.7875]])

In [29]:
Svнм =  C.dot(Sнм)
Svнм

array([[222.2857+101.27635694j],
       [ 29.575  +13.47476809j],
       [ 29.575  +13.47476809j],
       [192.7107 +87.80158886j],
       [  2.9575  +1.34747681j],
       [189.7532 +86.45411205j],
       [ 41.405  +18.86467532j],
       [ 11.83    +5.38990723j],
       [ 11.83    +5.38990723j],
       [ 29.575  +13.47476809j],
       [ 29.575  +13.47476809j],
       [  7.4529  +3.39564156j],
       [  7.4529  +3.39564156j],
       [140.8953 +64.19379517j],
       [  2.9575  +1.34747681j],
       [ 29.575  +13.47476809j],
       [ 29.575  +13.47476809j],
       [108.3628 +49.37155027j],
       [ 11.83    +5.38990723j],
       [ 11.83    +5.38990723j],
       [  4.732   +2.15596289j],
       [ 91.8008 +41.82568014j],
       [  7.4529  +3.39564156j],
       [ 48.8579 +22.26031688j],
       [ 29.575  +13.47476809j],
       [ 19.2829  +8.78554879j],
       [ 11.83    +5.38990723j],
       [ 11.83    +5.38990723j],
       [  7.4529  +3.39564156j],
       [  7.4529  +3.39564156j],
       [ 3

In [30]:
df = pd.DataFrame({'vetki':model,
                   'P_нб':np.squeeze(np.asarray(Svнб)).real,
                   'Q_нб':np.squeeze(np.asarray(Svнб)).imag,
                   'P_нм':np.squeeze(np.asarray(Svнм)).real,
                   'Q_нм':np.squeeze(np.asarray(Svнм)).imag,
                   'Iветви_нб':abs(np.squeeze(np.asarray(Svнб))/(Unom * pow(3,0.5))),
                   'Iветви_нм':abs(np.squeeze(np.asarray(Svнм))/(Unom * pow(3,0.5)))})
df

vetki       P_нб        Q_нб      P_нм        Q_нм  Iветви_нб  Iветви_нм
0     1-2  1111.4285  506.381785  222.2857  101.276357  70.514675  14.102935
1     2-3   147.8750   67.373840   29.5750   13.474768   9.381942   1.876388
2     3-4   147.8750   67.373840   29.5750   13.474768   9.381942   1.876388
3     2-5   963.5535  439.007944  192.7107   87.801589  61.132733  12.226547
4     5-6    14.7875    6.737384    2.9575    1.347477   0.938194   0.187639
5     5-7   948.7660  432.270560  189.7532   86.454112  60.194539  12.038908
6     7-8   207.0250   94.323377   41.4050   18.864675  13.134719   2.626944
7     8-9    59.1500   26.949536   11.8300    5.389907   3.752777   0.750555
8    9-10    59.1500   26.949536   11.8300    5.389907   3.752777   0.750555
9    8-11   147.8750   67.373840   29.5750   13.474768   9.381942   1.876388
10  11-12   147.8750   67.373840   29.5750   13.474768   9.381942   1.876388
11   7-13    37.2645   16.978208    7.4529    3.395642   2.364249   0.472850
12  13-14    37.2645   16.978208    7.4529    3.395642   2.364249   0.472850
13   7-15   704.4765  320.968976  140.8953   64.193795  44.695571   8.939114
14  15-16    14.7875    6.737384    2.9575    1.347477   0.938194   0.187639
15  15-17   147.8750   67.373840   29.5750   13.474768   9.381942   1.876388
16  17-18   147.8750   67.373840   29.5750   13.474768   9.381942   1.876388
17  15-19   541.8140  246.857751  108.3628   49.371550  34.375435   6.875087
18  19-20    59.1500   26.949536   11.8300    5.389907   3.752777   0.750555
19  20-21    59.1500   26.949536   11.8300    5.389907   3.752777   0.750555
20  19-22    23.6600   10.779814    4.7320    2.155963   1.501111   0.300222
21  19-23   459.0040  209.128401   91.8008   41.825680  29.121548   5.824310
22  23-24    37.2645   16.978208    7.4529    3.395642   2.364249   0.472850
23  23-25   244.2895  111.301584   48.8579   22.260317  15.498968   3.099794
24  25-26   147.8750   67.373840   29.5750   13.474768   9.381942   1.876388
25  25-27    96.4145   43.927744   19.2829    8.785549   6.117026   1.223405
26  27-28    59.1500   26.949536   11.8300    5.389907   3.752777   0.750555
27  28-29    59.1500   26.949536   11.8300    5.389907   3.752777   0.750555
28  27-30    37.2645   16.978208    7.4529    3.395642   2.364249   0.472850
29  30-31    37.2645   16.978208    7.4529    3.395642   2.364249   0.472850
30  23-32   177.4500   80.848609   35.4900   16.169722  11.258330   2.251666
31  32-33   147.8750   67.373840   29.5750   13.474768   9.381942   1.876388
32  33-34   147.8750   67.373840   29.5750   13.474768   9.381942   1.876388
33  32-35    29.5750   13.474768    5.9150    2.694954   1.876388   0.375278
34  35-36    14.7875    6.737384    2.9575    1.347477   0.938194   0.187639
35  35-37    14.7875    6.737384    2.9575    1.347477   0.938194   0.187639
36  37-38    14.7875    6.737384    2.9575    1.347477   0.938194   0.187639

In [31]:
df.to_excel("таблица_потоков.xlsx")

In [32]:
import sqlite3
import numpy as np


def vetvi():
    R = []
    X = []
    with open("линии.txt", 'r', encoding="utf-8") as f:
        with sqlite3.connect("server_db.db") as my_data:
            sql = my_data.cursor()
            for i in f.readlines():
                sql.execute(f"SELECT r0,x0 FROM provod WHERE mark_provod = '{i.strip().split()[1]}'")
                if sql.fetchone() is None:
                    sql.execute(f"SELECT rt,xt FROM trans2 WHERE mark_trans = '{i.strip().split()[1]}'")
                    r, x = map(float, sql.fetchone())
                    R.append(r)
                    X.append(x)
                else:
                    sql.execute(f"SELECT r0,x0 FROM provod WHERE mark_provod = '{i.strip().split()[1]}'")
                    r, x = map(float, sql.fetchone())
                    length = float(i.strip().split()[2])
                    R.append(r * length)
                    X.append(x * length)

    Z = np.zeros(shape=(len(R), len(X))).astype(complex)
    np.fill_diagonal(Z, [complex(R[i], X[i]) for i in range(len(X))])

    return Z


def main():
    print(vetvi())


if __name__ == "__main__":
    main()


[[  1.05963  +0.85215j   0.       +0.j        0.       +0.j      ...
    0.       +0.j        0.       +0.j        0.       +0.j     ]
 [  0.       +0.j        0.4505   +0.19398j   0.       +0.j      ...
    0.       +0.j        0.       +0.j        0.       +0.j     ]
 [  0.       +0.j        0.       +0.j        6.53    +18.74j    ...
    0.       +0.j        0.       +0.j        0.       +0.j     ]
 ...
 [  0.       +0.j        0.       +0.j        0.       +0.j      ...
  121.72   +167.77j      0.       +0.j        0.       +0.j     ]
 [  0.       +0.j        0.       +0.j        0.       +0.j      ...
    0.       +0.j        0.731    +0.31476j   0.       +0.j     ]
 [  0.       +0.j        0.       +0.j        0.       +0.j      ...
    0.       +0.j        0.       +0.j      121.72   +167.77j   ]]


In [33]:
Z = vetvi()
Z.diagonal().imag

array([8.52150e-01, 1.93980e-01, 1.87400e+01, 1.58700e-01, 1.67770e+02,
       5.14050e-01, 3.75882e-01, 7.35660e-02, 5.45600e+01, 4.75800e-01,
       1.87400e+01, 3.21714e-01, 7.02700e+01, 4.79550e-01, 1.67770e+02,
       2.78160e-01, 1.87400e+01, 1.07210e-01, 3.33060e-01, 5.45600e+01,
       1.09700e+02, 3.86950e-01, 7.02700e+01, 2.91100e-01, 1.87400e+01,
       3.76980e-01, 1.48230e-01, 5.45600e+01, 4.04796e-01, 7.02700e+01,
       1.39080e-01, 4.75800e-01, 1.87400e+01, 3.16590e-01, 1.67770e+02,
       3.14760e-01, 1.67770e+02])

In [34]:
sopr = pd.DataFrame({'vetki':model,
                    "R":Z.diagonal().real,
                    "X":Z.diagonal().imag})
sopr

vetki           R           X
0     1-2    1.059630    0.852150
1     2-3    0.450500    0.193980
2     3-4    6.530000   18.740000
3     2-5    0.197340    0.158700
4     5-6  121.720000  167.770000
5     5-7    0.639210    0.514050
6     7-8    0.811330    0.375882
7     8-9    0.170850    0.073566
8    9-10   26.460000   54.560000
9    8-11    1.105000    0.475800
10  11-12    6.530000   18.740000
11   7-13    0.747150    0.321714
12  13-14   35.560000   70.270000
13   7-15    0.596310    0.479550
14  15-16  121.720000  167.770000
15  15-17    0.646000    0.278160
16  17-18    6.530000   18.740000
17  15-19    0.182106    0.107210
18  19-20    0.773500    0.333060
19  20-21   26.460000   54.560000
20  19-22   68.910000  109.700000
21  19-23    0.640920    0.386950
22  23-24   35.560000   70.270000
23  23-25    0.482160    0.291100
24  25-26    6.530000   18.740000
25  25-27    0.875500    0.376980
26  27-28    0.344250    0.148230
27  28-29   26.460000   54.560000
28  27-30    0.940100    0.404796
29  30-31   35.560000   70.270000
30  23-32    0.300200    0.139080
31  32-33    1.105000    0.475800
32  33-34    6.530000   18.740000
33  32-35    0.735250    0.316590
34  35-36  121.720000  167.770000
35  35-37    0.731000    0.314760
36  37-38  121.720000  167.770000

Объеденяем таблицы

In [44]:
sopr.to_excel("Soprotiv.xlsx")
full_table = df.merge(sopr,on = 'vetki')
full_table

vetki       P_нб        Q_нб      P_нм        Q_нм  Iветви_нб  Iветви_нм  \
0     1-2  1111.4285  506.381785  222.2857  101.276357  70.514675  14.102935   
1     2-3   147.8750   67.373840   29.5750   13.474768   9.381942   1.876388   
2     3-4   147.8750   67.373840   29.5750   13.474768   9.381942   1.876388   
3     2-5   963.5535  439.007944  192.7107   87.801589  61.132733  12.226547   
4     5-6    14.7875    6.737384    2.9575    1.347477   0.938194   0.187639   
5     5-7   948.7660  432.270560  189.7532   86.454112  60.194539  12.038908   
6     7-8   207.0250   94.323377   41.4050   18.864675  13.134719   2.626944   
7     8-9    59.1500   26.949536   11.8300    5.389907   3.752777   0.750555   
8    9-10    59.1500   26.949536   11.8300    5.389907   3.752777   0.750555   
9    8-11   147.8750   67.373840   29.5750   13.474768   9.381942   1.876388   
10  11-12   147.8750   67.373840   29.5750   13.474768   9.381942   1.876388   
11   7-13    37.2645   16.978208    7.4529    3.395642   2.364249   0.472850   
12  13-14    37.2645   16.978208    7.4529    3.395642   2.364249   0.472850   
13   7-15   704.4765  320.968976  140.8953   64.193795  44.695571   8.939114   
14  15-16    14.7875    6.737384    2.9575    1.347477   0.938194   0.187639   
15  15-17   147.8750   67.373840   29.5750   13.474768   9.381942   1.876388   
16  17-18   147.8750   67.373840   29.5750   13.474768   9.381942   1.876388   
17  15-19   541.8140  246.857751  108.3628   49.371550  34.375435   6.875087   
18  19-20    59.1500   26.949536   11.8300    5.389907   3.752777   0.750555   
19  20-21    59.1500   26.949536   11.8300    5.389907   3.752777   0.750555   
20  19-22    23.6600   10.779814    4.7320    2.155963   1.501111   0.300222   
21  19-23   459.0040  209.128401   91.8008   41.825680  29.121548   5.824310   
22  23-24    37.2645   16.978208    7.4529    3.395642   2.364249   0.472850   
23  23-25   244.2895  111.301584   48.8579   22.260317  15.498968   3.099794   
24  25-26   147.8750   67.373840   29.5750   13.474768   9.381942   1.876388   
25  25-27    96.4145   43.927744   19.2829    8.785549   6.117026   1.223405   
26  27-28    59.1500   26.949536   11.8300    5.389907   3.752777   0.750555   
27  28-29    59.1500   26.949536   11.8300    5.389907   3.752777   0.750555   
28  27-30    37.2645   16.978208    7.4529    3.395642   2.364249   0.472850   
29  30-31    37.2645   16.978208    7.4529    3.395642   2.364249   0.472850   
30  23-32   177.4500   80.848609   35.4900   16.169722  11.258330   2.251666   
31  32-33   147.8750   67.373840   29.5750   13.474768   9.381942   1.876388   
32  33-34   147.8750   67.373840   29.5750   13.474768   9.381942   1.876388   
33  32-35    29.5750   13.474768    5.9150    2.694954   1.876388   0.375278   
34  35-36    14.7875    6.737384    2.9575    1.347477   0.938194   0.187639   
35  35-37    14.7875    6.737384    2.9575    1.347477   0.938194   0.187639   
36  37-38    14.7875    6.737384    2.9575    1.347477   0.938194   0.187639   

             R           X  
0     1.059630    0.852150  
1     0.450500    0.193980  
2     6.530000   18.740000  
3     0.197340    0.158700  
4   121.720000  167.770000  
5     0.639210    0.514050  
6     0.811330    0.375882  
7     0.170850    0.073566  
8    26.460000   54.560000  
9     1.105000    0.475800  
10    6.530000   18.740000  
11    0.747150    0.321714  
12   35.560000   70.270000  
13    0.596310    0.479550  
14  121.720000  167.770000  
15    0.646000    0.278160  
16    6.530000   18.740000  
17    0.182106    0.107210  
18    0.773500    0.333060  
19   26.460000   54.560000  
20   68.910000  109.700000  
21    0.640920    0.386950  
22   35.560000   70.270000  
23    0.482160    0.291100  
24    6.530000   18.740000  
25    0.875500    0.376980  
26    0.344250    0.148230  
27   26.460000   54.560000  
28    0.940100    0.404796  
29   35.560000   70.270000  
30    0.300200    0.139080  
31    1.105000    0.475800  
32    

Найдем падения напряжения на участках

In [47]:
full_table["dU_нб"] = (full_table["P_нб"]*full_table["R"] + full_table["Q_нб"]*full_table["X"])/Unom
full_table["dU_нм"] = (full_table["P_нм"]*full_table["R"] + full_table["Q_нм"]*full_table["X"])/Unom
full_table

vetki       P_нб        Q_нб      P_нм        Q_нм  Iветви_нб  Iветви_нм  \
0     1-2  1111.4285  506.381785  222.2857  101.276357  70.514675  14.102935   
1     2-3   147.8750   67.373840   29.5750   13.474768   9.381942   1.876388   
2     3-4   147.8750   67.373840   29.5750   13.474768   9.381942   1.876388   
3     2-5   963.5535  439.007944  192.7107   87.801589  61.132733  12.226547   
4     5-6    14.7875    6.737384    2.9575    1.347477   0.938194   0.187639   
5     5-7   948.7660  432.270560  189.7532   86.454112  60.194539  12.038908   
6     7-8   207.0250   94.323377   41.4050   18.864675  13.134719   2.626944   
7     8-9    59.1500   26.949536   11.8300    5.389907   3.752777   0.750555   
8    9-10    59.1500   26.949536   11.8300    5.389907   3.752777   0.750555   
9    8-11   147.8750   67.373840   29.5750   13.474768   9.381942   1.876388   
10  11-12   147.8750   67.373840   29.5750   13.474768   9.381942   1.876388   
11   7-13    37.2645   16.978208    7.4529    3.395642   2.364249   0.472850   
12  13-14    37.2645   16.978208    7.4529    3.395642   2.364249   0.472850   
13   7-15   704.4765  320.968976  140.8953   64.193795  44.695571   8.939114   
14  15-16    14.7875    6.737384    2.9575    1.347477   0.938194   0.187639   
15  15-17   147.8750   67.373840   29.5750   13.474768   9.381942   1.876388   
16  17-18   147.8750   67.373840   29.5750   13.474768   9.381942   1.876388   
17  15-19   541.8140  246.857751  108.3628   49.371550  34.375435   6.875087   
18  19-20    59.1500   26.949536   11.8300    5.389907   3.752777   0.750555   
19  20-21    59.1500   26.949536   11.8300    5.389907   3.752777   0.750555   
20  19-22    23.6600   10.779814    4.7320    2.155963   1.501111   0.300222   
21  19-23   459.0040  209.128401   91.8008   41.825680  29.121548   5.824310   
22  23-24    37.2645   16.978208    7.4529    3.395642   2.364249   0.472850   
23  23-25   244.2895  111.301584   48.8579   22.260317  15.498968   3.099794   
24  25-26   147.8750   67.373840   29.5750   13.474768   9.381942   1.876388   
25  25-27    96.4145   43.927744   19.2829    8.785549   6.117026   1.223405   
26  27-28    59.1500   26.949536   11.8300    5.389907   3.752777   0.750555   
27  28-29    59.1500   26.949536   11.8300    5.389907   3.752777   0.750555   
28  27-30    37.2645   16.978208    7.4529    3.395642   2.364249   0.472850   
29  30-31    37.2645   16.978208    7.4529    3.395642   2.364249   0.472850   
30  23-32   177.4500   80.848609   35.4900   16.169722  11.258330   2.251666   
31  32-33   147.8750   67.373840   29.5750   13.474768   9.381942   1.876388   
32  33-34   147.8750   67.373840   29.5750   13.474768   9.381942   1.876388   
33  32-35    29.5750   13.474768    5.9150    2.694954   1.876388   0.375278   
34  35-36    14.7875    6.737384    2.9575    1.347477   0.938194   0.187639   
35  35-37    14.7875    6.737384    2.9575    1.347477   0.938194   0.187639   
36  37-38    14.7875    6.737384    2.9575    1.347477   0.938194   0.187639   

             R           X       dU_нб      dU_нм  
0     1.059630    0.852150  160.921622  32.184324  
1     0.450500    0.193980    7.968687   1.593737  
2     6.530000   18.740000  222.820952  44.564190  
3     0.197340    0.158700   25.981821   5.196364  
4   121.720000  167.770000  293.026542  58.605308  
5     0.639210    0.514050   82.866940  16.573388  
6     0.811330    0.375882   20.342005   4.068401  
7     0.170850    0.073566    1.208835   0.241767  
8    26.460000   54.560000  303.547569  60.709514  
9     1.105000    0.475800   19.545835   3.909167  
10    6.530000   18.740000  222.820952  44.564190  
11    0.747150    0.321714    3.330430   0.666086  
12   35.560000   70.270000  251.818428  50.363686  
13    0.596310    0.479550   57.400705  11.480141  
14  121.720000  167.770000  293.026542  58.605308  
15    0.646000    0.278160   11.426796   2.285359  
16    6.530000   18.740000  222.820952  44.564190  
17    0.182106    0.107210 