In [3]:
import sqlite3
import numpy as np
import pandas as pd

def nagruzka(name_list,k,cosa,m):
    Unom = 10
    res_list = []
    with open(name_list, 'r', encoding='utf-8') as f:
        with sqlite3.connect("server_db.db") as my_data:
            sql = my_data.cursor()
            for i in f.readlines():
                if i.strip().split()[1] == '0':
                    res_list.append(0)
                elif len(i.strip().split()[1:]) == 1 and i.strip().split()[1].endswith('n') == False:
                    sql.execute(f"SELECT s FROM trans2 WHERE mark_trans = '{i.strip().split()[1]}'")
                    res_list.append(float(sql.fetchone()[0]))
                elif len(i.strip().split()[1:]) == 1 and i.strip().split()[1].endswith('n') == True:
                    sql.execute(f"SELECT pxx,qxx FROM trans2 WHERE mark_trans = '{i.strip().split()[1][:-1]}'")
                    pxx, qxx = map(float, sql.fetchone())
                    res_list.append(complex(pxx, qxx))
                else:
                    my_list = (i.strip().split()[1:])
                    my_list.remove("+")
                    result = 0
                    for i in my_list:
                        sql.execute(f"SELECT pxx,qxx FROM trans2 WHERE mark_trans = '{i}'")
                        pxx, qxx = map(float, sql.fetchone())
                        result += complex(pxx, qxx)
                    res_list.append(result)

    res_list.remove(0)
    
    Icp_max = (sum(res_list)*k)/(Unom*pow(3,0.5))
    Iнб = [(Icp_max*i)/sum(res_list) for i in res_list]
    Pнб = [i*cosa*Unom*pow(3,0.5) for i in Iнб]
    Qнб = [i*(1-cosa**2)**0.5*Unom*pow(3,0.5) for i in Iнб]
    Sнб = np.rot90(np.array([[complex(Pнб[i],Qнб[i]) for i in range(len(Pнб))]]),k=-1)
    Sнм = Sнб * m
    
    
    
    
    
    
    return -Sнб,-Sнм


def main():
    name_nagruzka = 'нагрузки.txt'
    print(nagruzka(name_list=name_nagruzka,k=0.65,cosa = 0.91,m = 0.2))


if __name__ == "__main__":
    main()


(array([[  -0.     -0.j        ],
       [  -0.     -0.j        ],
       [-147.875 -67.37384044j],
       [  -0.     -0.j        ],
       [ -14.7875 -6.73738404j],
       [  -0.     -0.j        ],
       [  -0.     -0.j        ],
       [  -0.     -0.j        ],
       [ -59.15  -26.94953617j],
       [  -0.     -0.j        ],
       [-147.875 -67.37384044j],
       [  -0.     -0.j        ],
       [ -37.2645-16.97820779j],
       [  -0.     -0.j        ],
       [ -14.7875 -6.73738404j],
       [  -0.     -0.j        ],
       [-147.875 -67.37384044j],
       [  -0.     -0.j        ],
       [  -0.     -0.j        ],
       [ -59.15  -26.94953617j],
       [ -23.66  -10.77981447j],
       [  -0.     -0.j        ],
       [ -37.2645-16.97820779j],
       [  -0.     -0.j        ],
       [-147.875 -67.37384044j],
       [  -0.     -0.j        ],
       [  -0.     -0.j        ],
       [ -59.15  -26.94953617j],
       [  -0.     -0.j        ],
       [ -37.2645-16.97820779j],
       [ 

Функция возвращает нагрузки(наибольшие и наименьшие) в виде матриц

In [16]:
name_nagruzka = 'нагрузки.txt'
Sнб,Sнм = nagruzka(name_list=name_nagruzka,k=0.65,cosa = 0.91,m = 0.2)
Unom = 10

In [102]:
Sнб

array([[  -0.     -0.j        ],
       [  -0.     -0.j        ],
       [-147.875 -67.37384044j],
       [  -0.     -0.j        ],
       [ -14.7875 -6.73738404j],
       [  -0.     -0.j        ],
       [  -0.     -0.j        ],
       [  -0.     -0.j        ],
       [ -59.15  -26.94953617j],
       [  -0.     -0.j        ],
       [-147.875 -67.37384044j],
       [  -0.     -0.j        ],
       [ -37.2645-16.97820779j],
       [  -0.     -0.j        ],
       [ -14.7875 -6.73738404j],
       [  -0.     -0.j        ],
       [-147.875 -67.37384044j],
       [  -0.     -0.j        ],
       [  -0.     -0.j        ],
       [ -59.15  -26.94953617j],
       [ -23.66  -10.77981447j],
       [  -0.     -0.j        ],
       [ -37.2645-16.97820779j],
       [  -0.     -0.j        ],
       [-147.875 -67.37384044j],
       [  -0.     -0.j        ],
       [  -0.     -0.j        ],
       [ -59.15  -26.94953617j],
       [  -0.     -0.j        ],
       [ -37.2645-16.97820779j],
       [  

In [103]:
Sнм

array([[ -0.     -0.j        ],
       [ -0.     -0.j        ],
       [-29.575 -13.47476809j],
       [ -0.     -0.j        ],
       [ -2.9575 -1.34747681j],
       [ -0.     -0.j        ],
       [ -0.     -0.j        ],
       [ -0.     -0.j        ],
       [-11.83   -5.38990723j],
       [ -0.     -0.j        ],
       [-29.575 -13.47476809j],
       [ -0.     -0.j        ],
       [ -7.4529 -3.39564156j],
       [ -0.     -0.j        ],
       [ -2.9575 -1.34747681j],
       [ -0.     -0.j        ],
       [-29.575 -13.47476809j],
       [ -0.     -0.j        ],
       [ -0.     -0.j        ],
       [-11.83   -5.38990723j],
       [ -4.732  -2.15596289j],
       [ -0.     -0.j        ],
       [ -7.4529 -3.39564156j],
       [ -0.     -0.j        ],
       [-29.575 -13.47476809j],
       [ -0.     -0.j        ],
       [ -0.     -0.j        ],
       [-11.83   -5.38990723j],
       [ -0.     -0.j        ],
       [ -7.4529 -3.39564156j],
       [ -0.     -0.j        ],
       [

Создаем матрицу С (матрицу коэффициентов токораспределения)

In [10]:
def first_matrix(model):
    start, end = [int(i.split('-')[0]) for i in model], [int(i.split('-')[1]) for i in model]
    M = np.zeros(shape=[max(end), max(start)])
    try:
        for i in range(len(start)):
            M[start[i]-1,i] = 1
            M[end[i]-1, i] = -1

        M = M[1:, :].astype(np.int32)

        return np.linalg.inv(M)
    except Exception as ex:

        return "Something_wrong"

def main():
    model =  "1-2 2-3 3-4 2-5 5-6 5-7 "\
        "7-8 8-9 9-10 8-11 11-12 7-13 13-14 7-15 "\
        "15-16 15-17 17-18 15-19 19-20 20-21 19-22 19-23 23-24 "\
        "23-25 25-26 25-27 27-28 28-29 27-30 30-31 "\
        "23-32 32-33 33-34 32-35 35-36 35-37 37-38".split()
    print(first_matrix(model))

if __name__ == '__main__':
    main()

[[-1. -1. -1. ... -1. -1. -1.]
 [-0. -1. -1. ... -0. -0. -0.]
 [-0. -0. -1. ... -0. -0. -0.]
 ...
 [-0. -0. -0. ... -1. -0. -0.]
 [-0. -0. -0. ... -0. -1. -1.]
 [-0. -0. -0. ... -0. -0. -1.]]


Нумерация ветвей

In [12]:
model =  "1-2 2-3 3-4 2-5 5-6 5-7 "\
        "7-8 8-9 9-10 8-11 11-12 7-13 13-14 7-15 "\
        "15-16 15-17 17-18 15-19 19-20 20-21 19-22 19-23 23-24 "\
        "23-25 25-26 25-27 27-28 28-29 27-30 30-31 "\
        "23-32 32-33 33-34 32-35 35-36 35-37 37-38".split()
model

['1-2',
 '2-3',
 '3-4',
 '2-5',
 '5-6',
 '5-7',
 '7-8',
 '8-9',
 '9-10',
 '8-11',
 '11-12',
 '7-13',
 '13-14',
 '7-15',
 '15-16',
 '15-17',
 '17-18',
 '15-19',
 '19-20',
 '20-21',
 '19-22',
 '19-23',
 '23-24',
 '23-25',
 '25-26',
 '25-27',
 '27-28',
 '28-29',
 '27-30',
 '30-31',
 '23-32',
 '32-33',
 '33-34',
 '32-35',
 '35-36',
 '35-37',
 '37-38']

In [13]:
C = first_matrix(model=model)
C

array([[-1., -1., -1., ..., -1., -1., -1.],
       [-0., -1., -1., ..., -0., -0., -0.],
       [-0., -0., -1., ..., -0., -0., -0.],
       ...,
       [-0., -0., -0., ..., -1., -0., -0.],
       [-0., -0., -0., ..., -0., -1., -1.],
       [-0., -0., -0., ..., -0., -0., -1.]])

Найдем потоки, которые протекают по нашим ветвям в режимах наибольших и меньших нагрузок

In [14]:
Svнб =  C.dot(Sнб)
Svнб

array([[1111.4285+506.38178471j],
       [ 147.875  +67.37384044j],
       [ 147.875  +67.37384044j],
       [ 963.5535+439.00794428j],
       [  14.7875  +6.73738404j],
       [ 948.766 +432.27056023j],
       [ 207.025  +94.32337661j],
       [  59.15   +26.94953617j],
       [  59.15   +26.94953617j],
       [ 147.875  +67.37384044j],
       [ 147.875  +67.37384044j],
       [  37.2645 +16.97820779j],
       [  37.2645 +16.97820779j],
       [ 704.4765+320.96897583j],
       [  14.7875  +6.73738404j],
       [ 147.875  +67.37384044j],
       [ 147.875  +67.37384044j],
       [ 541.814 +246.85775135j],
       [  59.15   +26.94953617j],
       [  59.15   +26.94953617j],
       [  23.66   +10.77981447j],
       [ 459.004 +209.12840071j],
       [  37.2645 +16.97820779j],
       [ 244.2895+111.3015844j ],
       [ 147.875  +67.37384044j],
       [  96.4145 +43.92774396j],
       [  59.15   +26.94953617j],
       [  59.15   +26.94953617j],
       [  37.2645 +16.97820779j],
       [  37.2

In [15]:
Svнм =  C.dot(Sнм)
Svнм

array([[222.2857+101.27635694j],
       [ 29.575  +13.47476809j],
       [ 29.575  +13.47476809j],
       [192.7107 +87.80158886j],
       [  2.9575  +1.34747681j],
       [189.7532 +86.45411205j],
       [ 41.405  +18.86467532j],
       [ 11.83    +5.38990723j],
       [ 11.83    +5.38990723j],
       [ 29.575  +13.47476809j],
       [ 29.575  +13.47476809j],
       [  7.4529  +3.39564156j],
       [  7.4529  +3.39564156j],
       [140.8953 +64.19379517j],
       [  2.9575  +1.34747681j],
       [ 29.575  +13.47476809j],
       [ 29.575  +13.47476809j],
       [108.3628 +49.37155027j],
       [ 11.83    +5.38990723j],
       [ 11.83    +5.38990723j],
       [  4.732   +2.15596289j],
       [ 91.8008 +41.82568014j],
       [  7.4529  +3.39564156j],
       [ 48.8579 +22.26031688j],
       [ 29.575  +13.47476809j],
       [ 19.2829  +8.78554879j],
       [ 11.83    +5.38990723j],
       [ 11.83    +5.38990723j],
       [  7.4529  +3.39564156j],
       [  7.4529  +3.39564156j],
       [ 3

In [17]:
df = pd.DataFrame({'vetki':model,
                   'Svetki_нб':np.squeeze(np.asarray(Svнб)),
                   'Svetki_нм':np.squeeze(np.asarray(Svнм)),
                   'Iветви_нб':np.squeeze(np.asarray(Svнб))/(Unom * pow(3,0.5)),
                   'Iветви_нм':np.squeeze(np.asarray(Svнм))/(Unom * pow(3,0.5))})
df

vetki                Svetki_нб               Svetki_нм  \
0     1-2  1111.428500+506.381785j  222.285700+101.276357j   
1     2-3  147.8750000+67.3738400j  29.5750000+13.4747680j   
2     3-4  147.8750000+67.3738400j  29.5750000+13.4747680j   
3     2-5   963.553500+439.007944j   192.710700+87.801589j   
4     5-6  14.78750000+6.73738400j  2.95750000+1.34747700j   
5     5-7   948.766000+432.270560j   189.753200+86.454112j   
6     7-8  207.0250000+94.3233770j  41.4050000+18.8646750j   
7     8-9   59.1500000+26.9495360j   11.8300000+5.3899070j   
8    9-10   59.1500000+26.9495360j   11.8300000+5.3899070j   
9    8-11  147.8750000+67.3738400j  29.5750000+13.4747680j   
10  11-12  147.8750000+67.3738400j  29.5750000+13.4747680j   
11   7-13   37.2645000+16.9782080j  7.45290000+3.39564200j   
12  13-14   37.2645000+16.9782080j  7.45290000+3.39564200j   
13   7-15   704.476500+320.968976j   140.895300+64.193795j   
14  15-16  14.78750000+6.73738400j  2.95750000+1.34747700j   
15  15-17  147.8750000+67.3738400j  29.5750000+13.4747680j   
16  17-18  147.8750000+67.3738400j  29.5750000+13.4747680j   
17  15-19   541.814000+246.857751j   108.362800+49.371550j   
18  19-20   59.1500000+26.9495360j   11.8300000+5.3899070j   
19  20-21   59.1500000+26.9495360j   11.8300000+5.3899070j   
20  19-22   23.6600000+10.7798140j  4.73200000+2.15596300j   
21  19-23   459.004000+209.128401j  91.8008000+41.8256800j   
22  23-24   37.2645000+16.9782080j  7.45290000+3.39564200j   
23  23-25   244.289500+111.301584j  48.8579000+22.2603170j   
24  25-26  147.8750000+67.3738400j  29.5750000+13.4747680j   
25  25-27   96.4145000+43.9277440j   19.2829000+8.7855490j   
26  27-28   59.1500000+26.9495360j   11.8300000+5.3899070j   
27  28-29   59.1500000+26.9495360j   11.8300000+5.3899070j   
28  27-30   37.2645000+16.9782080j  7.45290000+3.39564200j   
29  30-31   37.2645000+16.9782080j  7.45290000+3.39564200j   
30  23-32  177.4500000+80.8486090j  35.4900000+16.1697220j   
31  32-33  147.8750000+67.3738400j  29.5750000+13.4747680j   
32  33-34  147.8750000+67.3738400j  29.5750000+13.4747680j   
33  32-35   29.5750000+13.4747680j  5.91500000+2.69495400j   
34  35-36  14.78750000+6.73738400j  2.95750000+1.34747700j   
35  35-37  14.78750000+6.73738400j  2.95750000+1.34747700j   
36  37-38  14.78750000+6.73738400j  2.95750000+1.34747700j   

               Iветви_нб            Iветви_нм  
0   64.168354+29.235966j  12.833671+5.847193j  
1   8.5375670+3.8898300j   1.707513+0.777966j  
2   8.5375670+3.8898300j   1.707513+0.777966j  
3   55.630787+25.346135j  11.126157+5.069227j  
4   0.8537570+0.3889830j   0.170751+0.077797j  
5   54.777031+24.957152j  10.955406+4.991430j  
6    11.952594+5.445763j   2.390519+1.089153j  
7   3.4150270+1.5559320j   0.683005+0.311186j  
8   3.4150270+1.5559320j   0.683005+0.311186j  
9   8.5375670+3.8898300j   1.707513+0.777966j  
10  8.5375670+3.8898300j   1.707513+0.777966j  
11  2.1514670+0.9802370j   0.430293+0.196047j  
12  2.1514670+0.9802370j   0.430293+0.196047j  
13  40.672970+18.531152j   8.134594+3.706230j  
14  0.8537570+0.3889830j   0.170751+0.077797j  
15  8.5375670+3.8898300j   1.707513+0.777966j  
16  8.5375670+3.8898300j   1.707513+0.777966j  
17  31.281646+14.252339j   6.256329+2.850468j  
18  3.4150270+1.5559320j   0.683005+0.311186j  
19  3.4150270+1.5559320j   0.683005+0.311186j  
20  1.3660110+0.6223730j   0.273202+0.124475j  
21  26.500608+12.074034j   5.300122+2.414807j  
22  2.1514670+0.9802370j   0.430293+0.196047j  
23   14.104061+6.426000j   2.820812+1.285200j  
24  8.5375670+3.8898300j   1.707513+0.777966j  
25  5.5664940+2.5361690j   1.113299+0.507234j  
26  3.4150270+1.5559320j   0.683005+0.311186j  
27  3.4150270+1.5559320j   0.683005+0.311186j  
28  2.1514670+0.9802370j   0.430293+0.196047j  
29  2.1514670+0.9802370j   0.430293+0.196047j  
30   10.245081+4.667797j   2.049016+0.933559j  
31  8.5375670+3.8898300j   1.707513+0.777966j  
32  8.5375670+3.8898300j   1.707513+0.777966j  
33  1.7075130+0